services:
  postgres:
    image: postgres:latest
    container_name: kino_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kino
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data
    restart: always
volumes:
  db_data: