services:
  postgres:
    image: postgres:latest
    container_name: kino_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kino
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data
    restart: always
    networks:
      - app-network
  tomcat_server:
    image: tomcat:9-jdk8-corretto
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ../target/system-rezerwacji-biletow-backend-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/kin_app.war
    networks:
      - app-network
volumes:
  db_data:

networks:
  app-network:
    driver: bridge